/** @types {import('tailwindcss').Config} */

module.exports = {
    darkMode: ['class'],
    content: [
        './src/**/*.{js,ts,jsx,tsx}',
        './src/components/**/*.{js,jsx,ts,tsx}',
        './node_modules/react-tailwindcss-datepicker/dist/index.esm.js',
    ],
    theme: {
        truncate: {
            lines: {
                2: '2',
                3: '3',
            },
        },
        fontFamily: {
            sans: [
                'Pretendard',
                '-apple-system',
                'BlinkMacSystemFont',
                'system-ui',
                'Roboto',
                'Helvetica Neue',
                'Segoe UI',
                'Apple SD Gothic Neo',
                'Noto Sans KR',
                'Malgun Gothic',
                'sans-serif',
            ],
        },
        extend: {
            colors: {
                'brand-1': '#0066FF',
                'stroke-gray': '#e5e7eb',
                primaryColor: {
                    weak: '#F6F6FE',
                    bg: '#EFEFFD',
                    700: '#9D9FF5',
                    800: '#7D7FF1',
                    900: '#5C5FEE',
                },
                gray: {
                    50: '#F9F9FB',
                    100: '#F4F4F6',
                    150: '#EEEFF1',
                    200: '#E5E7EB',
                    300: '#D1D5DB',
                    350: '#BBBFC9',
                    400: '#9CA3AF',
                    500: '#6B7280',
                    600: '#4B5563',
                    700: '#374151',
                    800: '#1F2937',
                    900: '#111827',
                },
                greenColor: {
                    200: '#BBF7D0',
                    400: '#4ADE80',
                },
                redColor: {
                    200: '#FECACA',
                    400: '#F87171',
                },
                yellowColor: {
                    100: '#FFFBEC',
                    200: '#F6DAB9',
                    300: '#D97707',
                    400: '#78350F',
                },
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                chart: {
                    1: 'hsl(var(--chart-1))',
                    2: 'hsl(var(--chart-2))',
                    3: 'hsl(var(--chart-3))',
                    4: 'hsl(var(--chart-4))',
                    5: 'hsl(var(--chart-5))',
                },
            },
            fontSize: {
                10: ['0.625rem', {lineHeight: '1rem'}],
                11: ['0.6875rem', {lineHeight: '1rem'}],
                12: ['0.75rem', {lineHeight: '1rem'}],
                13: ['0.8125rem', {lineHeight: '1.125rem'}],
                14: ['0.875rem', {lineHeight: '1.25rem'}],
                15: ['0.9375rem', {lineHeight: '1.375rem'}],
                16: ['1rem', {lineHeight: '1.5rem'}],
                17: ['1.0625rem', {lineHeight: '1.625rem'}],
                18: ['1.125rem', {lineHeight: '1.75rem'}],
                19: ['1.1875rem', {lineHeight: '1.875rem'}],
                20: ['1.25rem', {lineHeight: '1.75rem'}],
                24: ['1.5rem', {lineHeight: '2rem'}],
                28: ['1.75rem', {lineHeight: '2rem'}],
                30: ['1.875rem', {lineHeight: '2.25rem'}],
                32: ['2rem', {lineHeight: '2.75rem'}],
                36: ['2.25rem', {lineHeight: '2.5rem'}],
                48: ['3rem', {lineHeight: 1}],
                56: ['3.5rem', {lineHeight: '4.5rem'}],
                60: ['3.75rem', {lineHeight: 1}],
                72: ['4.5rem', {lineHeight: 1}],
                96: ['6rem', {lineHeight: 1}],
                128: ['8rem', {lineHeight: 1}],
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            keyframes: {
                'slide-left-infinite': {
                    '0%': {transform: 'translateX(0)'},
                    '100%': {transform: 'translateX(-100%)'},
                },
                'infinite-scroll': {
                    '0%': {transform: 'translateX(0)'},
                    '100%': {transform: 'translateX(-50%)'},
                },
            },
            animation: {
                'slide-left-infinite': 'slide-left-infinite 20s linear infinite',
                'infinite-scroll': 'infinite-scroll 20s linear infinite',
            },
            screens: {
                xs: '560px',
            },
        },
        container: {
            center: true,
        },
    },
    plugins: [require('@tailwindcss/typography'), require('daisyui'), require('tailwindcss-animate')],
    daisyui: {
        themes: [
            {
                v220728: {
                    primary: '#0066FF',
                    secondary: '#D926A9',
                    accent: '#1FB2A6',
                    neutral: '#f3f4f6',
                    'base-100': '#ffffff',
                    info: '#3ABFF8',
                    success: '#36D399',
                    warning: '#FBBD23',
                    error: '#F87272',
                },
            },
        ],
    },
    safelist: [
        'data-[state=active]:bg-background',
        'data-[state=active]:text-foreground',
        'data-[state=active]:shadow',
        'data-[state=active]:shadow-md',
        'data-[state=closed]:animate-accordion-up',
        'data-[state=open]:animate-accordion-down',
        'data-[state=checked]:bg-primary',
        'data-[state=checked]:text-primary-foreground',
        'data-[state=open]:animate-in',
        'data-[state=closed]:animate-out',
        'data-[state=closed]:fade-out-0',
        'data-[state=open]:fade-in-0',
        'data-[state=closed]:zoom-out-95',
        'data-[state=open]:zoom-in-95',
        'data-[state=closed]:slide-out-to-left-1/2',
        'data-[state=closed]:slide-out-to-top-[48%]',
        'data-[state=open]:slide-in-from-left-1/2',
        'data-[state=open]:slide-in-from-top-[48%]',
        'data-[state=active]:bg-scordi',
        'data-[state=active]:text-white',
    ],
};
