export enum SubscriptionStatus {
    FREE_TRIAL_STARTED = 'FREE_TRIAL_STARTED',
    FREE_TRIAL_EXPIRED = 'FREE_TRIAL_EXPIRED',
    PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
    PAYMENT_PENDING = 'PAYMENT_PENDING',
    PAYMENT_FAILURE = 'PAYMENT_FAILURE',
    PAUSED = 'PAUSED',
    CANCELED = 'CANCELED',
}
